
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND ARROW BLOCK_COMMENT CLASS COLON COMA COMMENT CONCAT_EQUALS DEC DIVIDE DOUBLE_COLON ECHO ELSE EQ EQUALS FALSE FLOAT FOR FUNCTION GT GTE ID IF INC LBRACE LBRACKET LPAREN LT LTE MINUS MINUS_EQUALS MODULO NEW NOT NOT_EQ NULL NUMBER OR PHP_CLOSE PHP_OPEN PHP_SHORT_OPEN PLUS PLUS_EQUALS POW PRIVATE PROTECTED PUBLIC QMARK RBRACE RBRACKET RETURN RPAREN SEMI STRING TIMES TRUE VARIABLE WHILEprogram : statement_liststatement_list : statement_list statement\n| statementstatement : assignment\n| print_statement\n| if_statement\n| class_definition\n| php_open\n| php_closephp_open : PHP_OPENphp_close : PHP_CLOSEassignment : VARIABLE EQUALS expression SEMIprint_statement : ECHO expression SEMIif_statement : IF LPAREN expression RPAREN block\n| IF LPAREN expression RPAREN block ELSE blockblock : LBRACE statement_list RBRACEclass_definition : CLASS ID LBRACE class_body RBRACEclass_body : class_body class_member\n| class_member\n| emptyclass_member : PUBLIC VARIABLE SEMI\n| PRIVATE VARIABLE SEMI\n| PROTECTED VARIABLE SEMI\n| FUNCTION ID LPAREN RPAREN blockexpression : VARIABLE\n| NUMBER\n| STRING\n| TRUE\n| FALSEempty :'
    
_lr_action_items = {'VARIABLE':([0,2,3,4,5,6,7,8,9,11,14,15,16,17,24,27,30,35,36,37,39,40,41,48,53,54,],[10,10,-3,-4,-5,-6,-7,-8,-9,19,-10,-11,-2,19,19,-13,-12,43,44,45,-14,10,-17,10,-15,-16,]),'ECHO':([0,2,3,4,5,6,7,8,9,14,15,16,27,30,39,40,41,48,53,54,],[11,11,-3,-4,-5,-6,-7,-8,-9,-10,-11,-2,-13,-12,-14,11,-17,11,-15,-16,]),'IF':([0,2,3,4,5,6,7,8,9,14,15,16,27,30,39,40,41,48,53,54,],[12,12,-3,-4,-5,-6,-7,-8,-9,-10,-11,-2,-13,-12,-14,12,-17,12,-15,-16,]),'CLASS':([0,2,3,4,5,6,7,8,9,14,15,16,27,30,39,40,41,48,53,54,],[13,13,-3,-4,-5,-6,-7,-8,-9,-10,-11,-2,-13,-12,-14,13,-17,13,-15,-16,]),'PHP_OPEN':([0,2,3,4,5,6,7,8,9,14,15,16,27,30,39,40,41,48,53,54,],[14,14,-3,-4,-5,-6,-7,-8,-9,-10,-11,-2,-13,-12,-14,14,-17,14,-15,-16,]),'PHP_CLOSE':([0,2,3,4,5,6,7,8,9,14,15,16,27,30,39,40,41,48,53,54,],[15,15,-3,-4,-5,-6,-7,-8,-9,-10,-11,-2,-13,-12,-14,15,-17,15,-15,-16,]),'$end':([1,2,3,4,5,6,7,8,9,14,15,16,27,30,39,41,53,54,],[0,-1,-3,-4,-5,-6,-7,-8,-9,-10,-11,-2,-13,-12,-14,-17,-15,-16,]),'RBRACE':([3,4,5,6,7,8,9,14,15,16,27,29,30,32,33,34,39,41,42,48,49,50,51,53,54,56,],[-3,-4,-5,-6,-7,-8,-9,-10,-11,-2,-13,-30,-12,41,-19,-20,-14,-17,-18,54,-21,-22,-23,-15,-16,-24,]),'EQUALS':([10,],[17,]),'NUMBER':([11,17,24,],[20,20,20,]),'STRING':([11,17,24,],[21,21,21,]),'TRUE':([11,17,24,],[22,22,22,]),'FALSE':([11,17,24,],[23,23,23,]),'LPAREN':([12,46,],[24,52,]),'ID':([13,38,],[25,46,]),'SEMI':([18,19,20,21,22,23,26,43,44,45,],[27,-25,-26,-27,-28,-29,30,49,50,51,]),'RPAREN':([19,20,21,22,23,28,52,],[-25,-26,-27,-28,-29,31,55,]),'LBRACE':([25,31,47,55,],[29,40,40,40,]),'PUBLIC':([29,32,33,34,42,49,50,51,54,56,],[35,35,-19,-20,-18,-21,-22,-23,-16,-24,]),'PRIVATE':([29,32,33,34,42,49,50,51,54,56,],[36,36,-19,-20,-18,-21,-22,-23,-16,-24,]),'PROTECTED':([29,32,33,34,42,49,50,51,54,56,],[37,37,-19,-20,-18,-21,-22,-23,-16,-24,]),'FUNCTION':([29,32,33,34,42,49,50,51,54,56,],[38,38,-19,-20,-18,-21,-22,-23,-16,-24,]),'ELSE':([39,54,],[47,-16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement_list':([0,40,],[2,48,]),'statement':([0,2,40,48,],[3,16,3,16,]),'assignment':([0,2,40,48,],[4,4,4,4,]),'print_statement':([0,2,40,48,],[5,5,5,5,]),'if_statement':([0,2,40,48,],[6,6,6,6,]),'class_definition':([0,2,40,48,],[7,7,7,7,]),'php_open':([0,2,40,48,],[8,8,8,8,]),'php_close':([0,2,40,48,],[9,9,9,9,]),'expression':([11,17,24,],[18,26,28,]),'class_body':([29,],[32,]),'class_member':([29,32,],[33,42,]),'empty':([29,],[34,]),'block':([31,47,55,],[39,53,56,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement_list','program',1,'p_program','parser.py',16),
  ('statement_list -> statement_list statement','statement_list',2,'p_statement_list','parser.py',20),
  ('statement_list -> statement','statement_list',1,'p_statement_list','parser.py',21),
  ('statement -> assignment','statement',1,'p_statement','parser.py',28),
  ('statement -> print_statement','statement',1,'p_statement','parser.py',29),
  ('statement -> if_statement','statement',1,'p_statement','parser.py',30),
  ('statement -> class_definition','statement',1,'p_statement','parser.py',31),
  ('statement -> php_open','statement',1,'p_statement','parser.py',32),
  ('statement -> php_close','statement',1,'p_statement','parser.py',33),
  ('php_open -> PHP_OPEN','php_open',1,'p_php_open','parser.py',38),
  ('php_close -> PHP_CLOSE','php_close',1,'p_php_close','parser.py',44),
  ('assignment -> VARIABLE EQUALS expression SEMI','assignment',4,'p_assignment','parser.py',50),
  ('print_statement -> ECHO expression SEMI','print_statement',3,'p_print_statement','parser.py',55),
  ('if_statement -> IF LPAREN expression RPAREN block','if_statement',5,'p_if_statement','parser.py',60),
  ('if_statement -> IF LPAREN expression RPAREN block ELSE block','if_statement',7,'p_if_statement','parser.py',61),
  ('block -> LBRACE statement_list RBRACE','block',3,'p_block','parser.py',70),
  ('class_definition -> CLASS ID LBRACE class_body RBRACE','class_definition',5,'p_class_definition','parser.py',76),
  ('class_body -> class_body class_member','class_body',2,'p_class_body','parser.py',80),
  ('class_body -> class_member','class_body',1,'p_class_body','parser.py',81),
  ('class_body -> empty','class_body',1,'p_class_body','parser.py',82),
  ('class_member -> PUBLIC VARIABLE SEMI','class_member',3,'p_class_member','parser.py',91),
  ('class_member -> PRIVATE VARIABLE SEMI','class_member',3,'p_class_member','parser.py',92),
  ('class_member -> PROTECTED VARIABLE SEMI','class_member',3,'p_class_member','parser.py',93),
  ('class_member -> FUNCTION ID LPAREN RPAREN block','class_member',5,'p_class_member','parser.py',94),
  ('expression -> VARIABLE','expression',1,'p_expression_basic','parser.py',112),
  ('expression -> NUMBER','expression',1,'p_expression_basic','parser.py',113),
  ('expression -> STRING','expression',1,'p_expression_basic','parser.py',114),
  ('expression -> TRUE','expression',1,'p_expression_basic','parser.py',115),
  ('expression -> FALSE','expression',1,'p_expression_basic','parser.py',116),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',124),
]
